export const PERMISSIONS = [
  'USERS_VIEW',
  'USERS_VIEW_SELF',
  'USERS_CREATE',
  'USERS_UPDATE',
  'USERS_UPDATE_SELF',
  'USERS_DELETE',
  'USERS_LOCK',
  'USERS_UNLOCK',
  'USERS_TAGS_MANAGE',
  'USERS_FAMILY_LINK',
  'USERS_UPLOAD_AVATAR',
  'USERS_UPLOAD_AVATAR_SELF',
  'AUTH_VIEW_SELF',
  'AUTH_MANAGE_SESSIONS',
  'AUTH_CHANGE_PASSWORD',
  'CONFESSIONS_VIEW',
  'CONFESSIONS_CREATE',
  'CONFESSIONS_ASSIGN_USER',
  'CONFESSIONS_SESSION_TYPES_MANAGE',
  'CONFESSIONS_ALERTS_VIEW',
  'CONFESSIONS_ALERTS_MANAGE',
  'CONFESSIONS_ANALYTICS_VIEW',
  'PASTORAL_VISITATIONS_VIEW',
  'PASTORAL_VISITATIONS_CREATE',
  'PASTORAL_VISITATIONS_ANALYTICS_VIEW',
];

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [...PERMISSIONS],
  ADMIN: [
    'USERS_VIEW',
    'USERS_VIEW_SELF',
    'USERS_CREATE',
    'USERS_UPDATE',
    'USERS_UPDATE_SELF',
    'USERS_DELETE',
    'USERS_LOCK',
    'USERS_UNLOCK',
    'USERS_TAGS_MANAGE',
    'USERS_FAMILY_LINK',
    'USERS_UPLOAD_AVATAR',
    'USERS_UPLOAD_AVATAR_SELF',
    'AUTH_VIEW_SELF',
    'AUTH_CHANGE_PASSWORD',
    'CONFESSIONS_VIEW',
    'CONFESSIONS_CREATE',
    'CONFESSIONS_ASSIGN_USER',
    'CONFESSIONS_SESSION_TYPES_MANAGE',
    'CONFESSIONS_ALERTS_VIEW',
    'CONFESSIONS_ALERTS_MANAGE',
    'CONFESSIONS_ANALYTICS_VIEW',
  ],
  USER: [
    'AUTH_VIEW_SELF',
    'AUTH_CHANGE_PASSWORD',
    'USERS_VIEW_SELF',
    'USERS_UPDATE_SELF',
    'USERS_UPLOAD_AVATAR_SELF',
  ],
};

export const PERMISSION_LABELS = {
  USERS_VIEW: 'عرض المستخدمين',
  USERS_VIEW_SELF: 'عرض الملف الشخصي',
  USERS_CREATE: 'إنشاء مستخدم',
  USERS_UPDATE: 'تعديل المستخدمين',
  USERS_UPDATE_SELF: 'تعديل الملف الشخصي',
  USERS_DELETE: 'حذف المستخدمين',
  USERS_LOCK: 'قفل الحسابات',
  USERS_UNLOCK: 'فتح الحسابات',
  USERS_TAGS_MANAGE: 'إدارة الوسوم',
  USERS_FAMILY_LINK: 'ربط أفراد العائلة',
  USERS_UPLOAD_AVATAR: 'رفع صور المستخدمين',
  USERS_UPLOAD_AVATAR_SELF: 'رفع الصورة الشخصية',
  AUTH_VIEW_SELF: 'عرض بيانات الحساب',
  AUTH_MANAGE_SESSIONS: 'إدارة الجلسات',
  AUTH_CHANGE_PASSWORD: 'تغيير كلمة المرور',
  CONFESSIONS_VIEW: 'عرض الاعترافات',
  CONFESSIONS_CREATE: 'إنشاء جلسة اعتراف',
  CONFESSIONS_ASSIGN_USER: 'إسناد المستخدمين للاعتراف',
  CONFESSIONS_SESSION_TYPES_MANAGE: 'إدارة أنواع الجلسات',
  CONFESSIONS_ALERTS_VIEW: 'عرض تنبيهات الاعتراف',
  CONFESSIONS_ALERTS_MANAGE: 'إدارة تنبيهات الاعتراف',
  CONFESSIONS_ANALYTICS_VIEW: 'عرض تحليلات الاعتراف',
  PASTORAL_VISITATIONS_VIEW: 'عرض الافتقاد',
  PASTORAL_VISITATIONS_CREATE: 'إنشاء زيارة افتقاد',
  PASTORAL_VISITATIONS_ANALYTICS_VIEW: 'عرض تحليلات الافتقاد',
};

export const PERMISSION_GROUPS = [
  {
    id: 'users',
    label: 'إدارة المستخدمين',
    permissions: [
      'USERS_VIEW',
      'USERS_VIEW_SELF',
      'USERS_CREATE',
      'USERS_UPDATE',
      'USERS_UPDATE_SELF',
      'USERS_DELETE',
      'USERS_LOCK',
      'USERS_UNLOCK',
      'USERS_TAGS_MANAGE',
      'USERS_FAMILY_LINK',
      'USERS_UPLOAD_AVATAR',
      'USERS_UPLOAD_AVATAR_SELF',
    ],
  },
  {
    id: 'auth',
    label: 'المصادقة',
    permissions: ['AUTH_VIEW_SELF', 'AUTH_MANAGE_SESSIONS', 'AUTH_CHANGE_PASSWORD'],
  },
  {
    id: 'confessions',
    label: 'الاعتراف',
    permissions: [
      'CONFESSIONS_VIEW',
      'CONFESSIONS_CREATE',
      'CONFESSIONS_ASSIGN_USER',
      'CONFESSIONS_SESSION_TYPES_MANAGE',
      'CONFESSIONS_ALERTS_VIEW',
      'CONFESSIONS_ALERTS_MANAGE',
      'CONFESSIONS_ANALYTICS_VIEW',
    ],
  },
  {
    id: 'visitations',
    label: 'الافتقاد',
    permissions: [
      'PASTORAL_VISITATIONS_VIEW',
      'PASTORAL_VISITATIONS_CREATE',
      'PASTORAL_VISITATIONS_ANALYTICS_VIEW',
    ],
  },
];
