export const WEEK_DAYS = [
  { value: 0, label: 'Sunday' },
  { value: 1, label: 'Monday' },
  { value: 2, label: 'Tuesday' },
  { value: 3, label: 'Wednesday' },
  { value: 4, label: 'Thursday' },
  { value: 5, label: 'Friday' },
  { value: 6, label: 'Saturday' },
];

export const AVAILABILITY_MODES = [
  { value: 'NONE' },
  { value: 'ALWAYS' },
  { value: 'DATE_RANGE' },
  { value: 'DATE_TIME_RANGE' },
  { value: 'SPECIFIC_DAYS' },
  { value: 'SPECIFIC_DAYS_TIME' },
  { value: 'SPECIFIC_DATES' },
  { value: 'SPECIFIC_DATES_TIME' },
];

export const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'textarea', label: 'Textarea' },
  { value: 'number', label: 'Number' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'date', label: 'Date' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'select', label: 'Select' },
  { value: 'image', label: 'Image' },
];

/*
 * Availability "families" collapse the eight backend modes into four intuitive
 * choices plus a "restrict to specific times" toggle. The picker in the UI
 * works with families; we only translate to/from the backend enum when saving
 * or loading, so the wire format and slot-generation semantics stay identical.
 */
export const AVAILABILITY_FAMILIES = ['ALWAYS', 'DATE', 'DAYS', 'DATES'];

export function modeToFamily(mode) {
  switch (mode) {
    case 'ALWAYS':
      return 'ALWAYS';
    case 'DATE_RANGE':
    case 'DATE_TIME_RANGE':
      return 'DATE';
    case 'SPECIFIC_DAYS':
    case 'SPECIFIC_DAYS_TIME':
      return 'DAYS';
    case 'SPECIFIC_DATES':
    case 'SPECIFIC_DATES_TIME':
    case 'DATE_TIME':
      return 'DATES';
    default:
      return 'ALWAYS';
  }
}

export function familySupportsTime(family) {
  return ['DATE', 'DAYS', 'DATES'].includes(family);
}

export function composeMode(family, restrictTimes) {
  switch (family) {
    case 'DATE':
      return restrictTimes ? 'DATE_TIME_RANGE' : 'DATE_RANGE';
    case 'DAYS':
      return restrictTimes ? 'SPECIFIC_DAYS_TIME' : 'SPECIFIC_DAYS';
    case 'DATES':
      return restrictTimes ? 'SPECIFIC_DATES_TIME' : 'SPECIFIC_DATES';
    case 'ALWAYS':
    default:
      return 'ALWAYS';
  }
}

export function isBookableMode(mode) {
  return mode !== 'NONE';
}

export function modeHasTime(mode) {
  return ['DATE_TIME_RANGE', 'SPECIFIC_DAYS_TIME', 'SPECIFIC_DATES_TIME', 'DATE_TIME'].includes(mode);
}

export function modeUsesAvailabilityRules(mode) {
  return !['NONE', 'ALWAYS'].includes(mode);
}

// Modes where slots come from a start/end time window (interval + duration used).
export function modeUsesTimeRange(mode) {
  return ['DATE_TIME_RANGE', 'SPECIFIC_DAYS_TIME'].includes(mode);
}

export function modeUsesDateRange(mode) {
  return ['DATE_RANGE', 'DATE_TIME_RANGE'].includes(mode);
}

export function modeUsesSpecificDays(mode) {
  return ['SPECIFIC_DAYS', 'SPECIFIC_DAYS_TIME'].includes(mode);
}

export function modeUsesSpecificDates(mode) {
  return ['SPECIFIC_DATES', 'SPECIFIC_DATES_TIME'].includes(mode);
}

export function modeUsesExactTimes(mode) {
  return ['SPECIFIC_DATES_TIME', 'DATE_TIME'].includes(mode);
}

// Duration + slot interval only matter when times are generated from a window.
export function modeUsesDuration(mode) {
  return modeUsesTimeRange(mode);
}

export function availabilityLabel(mode, tf) {
  switch (mode) {
    case 'NONE':
      return tf('bookings.public.modes.none', 'No availability');
    case 'ALWAYS':
      return tf('bookings.public.modes.always', 'Always available');
    case 'DATE_RANGE':
      return tf('bookings.public.modes.dateRange', 'Within a date range');
    case 'DATE_TIME_RANGE':
      return tf('bookings.public.modes.dateTimeRange', 'Within a date and time range');
    case 'SPECIFIC_DAYS':
      return tf('bookings.public.modes.specificDays', 'Specific days');
    case 'SPECIFIC_DAYS_TIME':
      return tf('bookings.public.modes.specificDaysTime', 'Specific days and times');
    case 'SPECIFIC_DATES':
      return tf('bookings.public.modes.specificDates', 'Specific dates');
    case 'SPECIFIC_DATES_TIME':
    case 'DATE_TIME':
      return tf('bookings.public.modes.specificDatesTime', 'Specific dates and times');
    default:
      return mode;
  }
}

/* ── Field keys are generated by the system, never typed by the admin ──────── */

const FIELD_KEY_PATTERN = /^[a-zA-Z][a-zA-Z0-9_]*$/;

export function isValidFieldKey(key) {
  return typeof key === 'string' && key.length <= 60 && FIELD_KEY_PATTERN.test(key);
}

// Turn a human label (Arabic or English) into a safe ascii key fragment.
export function slugifyFieldKey(label) {
  const base = String(label || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_{2,}/g, '_')
    .slice(0, 50);
  if (!base) return '';
  return /^[a-z]/.test(base) ? base : `field_${base}`;
}

/*
 * Produce a stable, unique, backend-valid key for every field.
 *  - Existing valid keys (edit mode) are preserved so saved bookings keep
 *    resolving their answers.
 *  - New fields are derived from their label, falling back to field_N when the
 *    label has no ascii characters (e.g. a purely Arabic label).
 *  - Collisions get a numeric suffix.
 */
export function buildFieldKeys(fields = []) {
  const used = new Set();
  return fields.map((field, index) => {
    let base = isValidFieldKey(field?.key)
      ? field.key
      : slugifyFieldKey(field?.label) || `field_${index + 1}`;
    base = base.slice(0, 55);

    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${base}_${suffix}`;
      suffix += 1;
    }
    used.add(candidate);
    return candidate;
  });
}

// Select option values are internal identifiers too — the admin only types the
// visible label and we derive a stable, unique value for each option.
export function buildOptionValues(options = []) {
  const used = new Set();
  return options.map((option, index) => {
    let base = (option?.value && String(option.value).trim())
      || slugifyFieldKey(option?.label)
      || `option_${index + 1}`;
    base = base.slice(0, 110);

    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${base}_${suffix}`;
      suffix += 1;
    }
    used.add(candidate);
    return candidate;
  });
}

export function createEmptyTypeForm() {
  return {
    id: null,
    name: '',
    description: '',
    instructions: '',
    isActive: true,
    availabilityMode: 'ALWAYS',
    durationMinutes: 30,
    slotIntervalMinutes: 30,
    capacity: 1,
    bookingHorizonDays: 60,
    availabilityConfig: {
      timezone: 'Africa/Cairo',
      timeRange: { startTime: '09:00', endTime: '17:00' },
      dateRange: { startDate: '', endDate: '' },
      specificDays: [],
      specificDates: [],
      exactDateTimes: [],
    },
    dynamicFields: [],
  };
}

export function mapTypeToForm(type) {
  const exactDatesFromLegacy = Array.isArray(type.availabilityConfig?.exactDateTimes)
    ? type.availabilityConfig.exactDateTimes.reduce((acc, entry) => {
      const existing = acc.find((item) => item.date === entry.date);
      if (existing) {
        existing.exactTimes = [
          ...new Set([...(existing.exactTimes || []), entry.time || '']),
        ]
          .filter(Boolean)
          .sort();
        return acc;
      }

      acc.push({
        date: entry.date || '',
        startTime: '',
        endTime: '',
        exactTimes: entry.time ? [entry.time] : [],
      });
      return acc;
    }, [])
    : [];

  const specificDates = Array.isArray(type.availabilityConfig?.specificDates)
    ? type.availabilityConfig.specificDates.map((entry) => ({
      date: entry.date || '',
      startTime: entry.startTime || '',
      endTime: entry.endTime || '',
      exactTimes: Array.isArray(entry.exactTimes) ? entry.exactTimes : [],
    }))
    : [];

  const mergedSpecificDates = [...specificDates];
  exactDatesFromLegacy.forEach((entry) => {
    if (mergedSpecificDates.some((item) => item.date === entry.date)) return;
    mergedSpecificDates.push(entry);
  });

  return {
    id: type.id,
    name: type.name || '',
    description: type.description || '',
    instructions: type.instructions || '',
    isActive: type.isActive !== false,
    availabilityMode:
      type.availabilityMode === 'DATE_TIME'
        ? 'SPECIFIC_DATES_TIME'
        : (type.availabilityMode || 'NONE'),
    durationMinutes: type.durationMinutes || 30,
    slotIntervalMinutes: type.slotIntervalMinutes || 30,
    capacity: type.capacity || 1,
    bookingHorizonDays: type.bookingHorizonDays || 60,
    availabilityConfig: {
      timezone: type.availabilityConfig?.timezone || 'Africa/Cairo',
      timeRange: {
        startTime: type.availabilityConfig?.timeRange?.startTime || '09:00',
        endTime: type.availabilityConfig?.timeRange?.endTime || '17:00',
      },
      dateRange: {
        startDate: type.availabilityConfig?.dateRange?.startDate || '',
        endDate: type.availabilityConfig?.dateRange?.endDate || '',
      },
      specificDays: Array.isArray(type.availabilityConfig?.specificDays)
        ? type.availabilityConfig.specificDays
        : [],
      specificDates: mergedSpecificDates,
      exactDateTimes: [],
    },
    dynamicFields: Array.isArray(type.dynamicFields)
      ? type.dynamicFields.map((field) => ({
        key: field.key || '',
        label: field.label || '',
        type: field.type || 'text',
        required: Boolean(field.required),
        placeholder: field.placeholder || '',
        helpText: field.helpText || '',
        options: Array.isArray(field.options)
          ? field.options.map((option) => ({
            label: option.label || '',
            value: option.value || '',
          }))
          : [],
      }))
      : [],
  };
}

export function serializeTypeForm(form) {
  const mode = form.availabilityMode;
  const bookable = isBookableMode(mode);
  const usesWindow = modeUsesTimeRange(mode);
  const fieldKeys = buildFieldKeys(form.dynamicFields);

  return {
    name: form.name.trim(),
    description: form.description.trim() || null,
    instructions: form.instructions.trim() || null,
    isActive: Boolean(form.isActive),
    availabilityMode: mode,
    // Duration + interval only mean something when slots are generated from a
    // window; for every other mode we fall back to the backend defaults instead
    // of persisting numbers the admin never actually configured.
    durationMinutes: usesWindow ? (Number(form.durationMinutes) || 30) : 30,
    slotIntervalMinutes: usesWindow ? (Number(form.slotIntervalMinutes) || 30) : 30,
    capacity: bookable ? (Number(form.capacity) || 1) : 1,
    bookingHorizonDays: bookable ? (Number(form.bookingHorizonDays) || 60) : 60,
    availabilityConfig: {
      timezone: form.availabilityConfig.timezone || 'Africa/Cairo',
      timeRange: {
        startTime: usesWindow ? (form.availabilityConfig.timeRange.startTime || null) : null,
        endTime: usesWindow ? (form.availabilityConfig.timeRange.endTime || null) : null,
      },
      dateRange: {
        startDate: modeUsesDateRange(mode)
          ? (form.availabilityConfig.dateRange.startDate || null)
          : null,
        endDate: modeUsesDateRange(mode)
          ? (form.availabilityConfig.dateRange.endDate || null)
          : null,
      },
      specificDays: modeUsesSpecificDays(mode) ? form.availabilityConfig.specificDays : [],
      specificDates: modeUsesSpecificDates(mode)
        ? form.availabilityConfig.specificDates
          .filter((entry) => entry.date)
          .map((entry) => ({
            date: entry.date,
            startTime: null,
            endTime: null,
            exactTimes: modeUsesExactTimes(mode)
              ? (entry.exactTimes || []).filter(Boolean)
              : [],
          }))
        : [],
      exactDateTimes: [],
    },
    dynamicFields: form.dynamicFields.map((field, index) => ({
      key: fieldKeys[index],
      label: field.label.trim(),
      type: field.type,
      required: Boolean(field.required),
      placeholder: field.placeholder.trim() || null,
      helpText: field.helpText.trim() || null,
      options: field.type === 'select'
        ? (() => {
          const labelled = field.options.filter((option) => option.label.trim());
          const values = buildOptionValues(labelled);
          return labelled.map((option, optionIndex) => ({
            label: option.label.trim(),
            value: values[optionIndex],
          }));
        })()
        : [],
    })),
  };
}
